# Generated by Django 5.0.1 on 2024-01-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("long_link", models.URLField()),
                ("short_link", models.CharField()),
            ],
        ),
    ]
