# Generated by Django 5.0.1 on 2024-01-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("long_link", models.URLField()),
                ("short_link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="links",
        ),
    ]
