# Generated by Django 5.0.1 on 2024-01-25 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0002_link_delete_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="short_link",
        ),
    ]
