# Generated by Django 5.0.1 on 2024-01-26 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0003_remove_link_short_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="long_link",
            new_name="link",
        ),
    ]
