# Generated by Django 5.0.1 on 2024-04-09 18:16

import shortener.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0004_rename_long_link_link_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="owner",
            field=models.ForeignKey(
                default=shortener.models.get_sentinel_user,
                on_delete=models.SET(shortener.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
