name: LnkShrt Build & Publish

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
          packages: write
        strategy:
          matrix:
            container: [frontend, backend]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log into Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and Publish Backend
              uses: docker/build-push-action@v5
              with:
                context: ./${{ matrix.container }}
                push: true
                tags: ghcr.io/tressims/lnkshrt_${{ matrix.container }}
